Added features such that issues labeled with cloudoffice print are resolved.
United-Codes/cloudofficeprint-java pull request #9
Opened 2021-12-10 09:59 UTC by ram-arthasoft

Added freeze pane property
Added watermark opacity,color,font ,size, orientation,
sign certificate with password
remove last page from output.
ipp printer status check
return output from AOP server.
added test configuration for these changes.

and updated documentation for these changes

2021-12-10 10:17 UTC, suniltandan commented on cloudofficeprint/src/main/java/com/cloudofficeprint/Output/PDFOptions.java
> +    public Integer getWatermarkOpacity(){
make documentation more clear that this is in percentage

2021-12-10 10:18 UTC, suniltandan commented on cloudofficeprint/src/main/java/com/cloudofficeprint/Output/PDFOptions.java
> +        this.watermarkSize = watermarkSize;
watermark fontsize instead of just watermark size

2021-12-10 10:18 UTC, suniltandan commented on cloudofficeprint/src/main/java/com/cloudofficeprint/Output/PDFOptions.java
> +        this.watermarkColor = watermarkColor;
clarify what is accepted in the string. the css values for colors is accepted

2021-12-10 10:18 UTC, suniltandan commented on cloudofficeprint/src/main/java/com/cloudofficeprint/Output/PDFOptions.java
> +        return signCertificateWithPassword;
not with password for just getSignCertificatePassword

2021-12-10 10:19 UTC, suniltandan commented on cloudofficeprint/src/main/java/com/cloudofficeprint/Output/PDFOptions.java
> +    public void setSignCertificateWithPassword(String signCertificateWithPassword){
rename method again without the withj

2021-12-10 10:26 UTC, suniltandan requested changes
please have a look at the comments and change appropriately

2022-12-13 09:44 UTC, ramchandra-kc commented
created another pull request that has the option available in this pull request

2022-12-13 09:44 UTC, closed without merging